// ============================================================================
// FC 26 team catalog — 100 real clubs from the game, distributed across the 14
// licensed leagues. No national teams. Data curated from SoFIFA / EA FC 26.
// Rosters (elencos) provided for the top 15 teams — the rest fall back to
// empty roster so the user can register squads manually inside the game.
// ============================================================================

window.FC_TEAM_CATALOG = [
  // ---------------- Premier League (15) --------------------------------
  { id: 'realmadrid',   name: 'Real Madrid',           league: 'La Liga',          country: 'ES', tier: 'top', ovr: 85 },
  { id: 'barcelona',    name: 'FC Barcelona',          league: 'La Liga',          country: 'ES', tier: 'top', ovr: 85 },
  { id: 'atleti',       name: 'Atlético de Madrid',    league: 'La Liga',          country: 'ES', tier: 'top', ovr: 82 },
  { id: 'athletic',     name: 'Athletic Club',         league: 'La Liga',          country: 'ES', tier: 'mid', ovr: 79 },
  { id: 'realsociedad', name: 'Real Sociedad',         league: 'La Liga',          country: 'ES', tier: 'mid', ovr: 78 },
  { id: 'betis',        name: 'Real Betis',            league: 'La Liga',          country: 'ES', tier: 'mid', ovr: 78 },
  { id: 'villarreal',   name: 'Villarreal CF',         league: 'La Liga',          country: 'ES', tier: 'mid', ovr: 79 },
  { id: 'valencia',     name: 'Valencia CF',           league: 'La Liga',          country: 'ES', tier: 'mid', ovr: 76 },
  { id: 'sevilla',      name: 'Sevilla FC',            league: 'La Liga',          country: 'ES', tier: 'mid', ovr: 76 },
  { id: 'girona',       name: 'Girona FC',             league: 'La Liga',          country: 'ES', tier: 'low', ovr: 74 },
  { id: 'getafe',       name: 'Getafe CF',             league: 'La Liga',          country: 'ES', tier: 'low', ovr: 73 },
  { id: 'rayo',         name: 'Rayo Vallecano',        league: 'La Liga',          country: 'ES', tier: 'low', ovr: 74 },
  // ---------------- Premier League (15) --------------------------------
  { id: 'mancity',      name: 'Manchester City',       league: 'Premier League',   country: 'EN', tier: 'top', ovr: 84 },
  { id: 'arsenal',      name: 'Arsenal',               league: 'Premier League',   country: 'EN', tier: 'top', ovr: 84 },
  { id: 'liverpool',    name: 'Liverpool',             league: 'Premier League',   country: 'EN', tier: 'top', ovr: 84 },
  { id: 'chelsea',      name: 'Chelsea',               league: 'Premier League',   country: 'EN', tier: 'top', ovr: 81 },
  { id: 'manutd',       name: 'Manchester United',     league: 'Premier League',   country: 'EN', tier: 'top', ovr: 80 },
  { id: 'tottenham',    name: 'Tottenham Hotspur',     league: 'Premier League',   country: 'EN', tier: 'top', ovr: 80 },
  { id: 'newcastle',    name: 'Newcastle United',      league: 'Premier League',   country: 'EN', tier: 'top', ovr: 80 },
  { id: 'astonvilla',   name: 'Aston Villa',           league: 'Premier League',   country: 'EN', tier: 'mid', ovr: 79 },
  { id: 'brighton',     name: 'Brighton & Hove Albion',league: 'Premier League',   country: 'EN', tier: 'mid', ovr: 77 },
  { id: 'westham',      name: 'West Ham United',       league: 'Premier League',   country: 'EN', tier: 'mid', ovr: 76 },
  { id: 'wolves',       name: 'Wolverhampton Wanderers',league: 'Premier League',  country: 'EN', tier: 'mid', ovr: 75 },
  { id: 'palace',       name: 'Crystal Palace',        league: 'Premier League',   country: 'EN', tier: 'mid', ovr: 76 },
  { id: 'fulham',       name: 'Fulham',                league: 'Premier League',   country: 'EN', tier: 'mid', ovr: 75 },
  { id: 'brentford',    name: 'Brentford',             league: 'Premier League',   country: 'EN', tier: 'low', ovr: 75 },
  { id: 'bournemouth',  name: 'AFC Bournemouth',       league: 'Premier League',   country: 'EN', tier: 'low', ovr: 74 },
  // ---------------- Serie A (12) ---------------------------------------
  { id: 'inter',        name: 'Inter',                 league: 'Serie A',          country: 'IT', tier: 'top', ovr: 83 },
  { id: 'milan',        name: 'AC Milan',              league: 'Serie A',          country: 'IT', tier: 'top', ovr: 81 },
  { id: 'juventus',     name: 'Juventus',              league: 'Serie A',          country: 'IT', tier: 'top', ovr: 80 },
  { id: 'napoli',       name: 'Napoli',                league: 'Serie A',          country: 'IT', tier: 'top', ovr: 81 },
  { id: 'atalanta',     name: 'Atalanta',              league: 'Serie A',          country: 'IT', tier: 'mid', ovr: 80 },
  { id: 'roma',         name: 'Roma',                  league: 'Serie A',          country: 'IT', tier: 'mid', ovr: 79 },
  { id: 'lazio',        name: 'Lazio',                 league: 'Serie A',          country: 'IT', tier: 'mid', ovr: 78 },
  { id: 'fiorentina',   name: 'Fiorentina',            league: 'Serie A',          country: 'IT', tier: 'mid', ovr: 77 },
  { id: 'bologna',      name: 'Bologna',               league: 'Serie A',          country: 'IT', tier: 'mid', ovr: 77 },
  { id: 'torino',       name: 'Torino',                league: 'Serie A',          country: 'IT', tier: 'low', ovr: 75 },
  { id: 'como',         name: 'Como',                  league: 'Serie A',          country: 'IT', tier: 'low', ovr: 74 },
  { id: 'genoa',        name: 'Genoa',                 league: 'Serie A',          country: 'IT', tier: 'low', ovr: 73 },
  // ---------------- Bundesliga (10) ------------------------------------
  { id: 'bayern',       name: 'FC Bayern München',     league: 'Bundesliga',       country: 'DE', tier: 'top', ovr: 84 },
  { id: 'leverkusen',   name: 'Bayer 04 Leverkusen',   league: 'Bundesliga',       country: 'DE', tier: 'top', ovr: 82 },
  { id: 'dortmund',     name: 'Borussia Dortmund',     league: 'Bundesliga',       country: 'DE', tier: 'top', ovr: 81 },
  { id: 'leipzig',      name: 'RB Leipzig',            league: 'Bundesliga',       country: 'DE', tier: 'top', ovr: 80 },
  { id: 'stuttgart',    name: 'VfB Stuttgart',         league: 'Bundesliga',       country: 'DE', tier: 'mid', ovr: 78 },
  { id: 'frankfurt',    name: 'Eintracht Frankfurt',   league: 'Bundesliga',       country: 'DE', tier: 'mid', ovr: 78 },
  { id: 'freiburg',     name: 'SC Freiburg',           league: 'Bundesliga',       country: 'DE', tier: 'mid', ovr: 76 },
  { id: 'bremen',       name: 'SV Werder Bremen',      league: 'Bundesliga',       country: 'DE', tier: 'low', ovr: 74 },
  { id: 'unionberlin',  name: 'Union Berlin',          league: 'Bundesliga',       country: 'DE', tier: 'low', ovr: 74 },
  { id: 'wolfsburg',    name: 'VfL Wolfsburg',         league: 'Bundesliga',       country: 'DE', tier: 'low', ovr: 74 },
  // ---------------- Ligue 1 (10) ---------------------------------------
  { id: 'psg',          name: 'Paris Saint-Germain',   league: 'Ligue 1',          country: 'FR', tier: 'top', ovr: 85 },
  { id: 'marseille',    name: 'Olympique de Marseille',league: 'Ligue 1',          country: 'FR', tier: 'top', ovr: 80 },
  { id: 'monaco',       name: 'AS Monaco',             league: 'Ligue 1',          country: 'FR', tier: 'mid', ovr: 79 },
  { id: 'lyon',         name: 'Olympique Lyonnais',    league: 'Ligue 1',          country: 'FR', tier: 'mid', ovr: 78 },
  { id: 'lille',        name: 'Lille OSC',             league: 'Ligue 1',          country: 'FR', tier: 'mid', ovr: 78 },
  { id: 'nice',         name: 'OGC Nice',              league: 'Ligue 1',          country: 'FR', tier: 'mid', ovr: 77 },
  { id: 'rennes',       name: 'Stade Rennais',         league: 'Ligue 1',          country: 'FR', tier: 'mid', ovr: 76 },
  { id: 'lens',         name: 'RC Lens',               league: 'Ligue 1',          country: 'FR', tier: 'mid', ovr: 76 },
  { id: 'toulouse',     name: 'Toulouse FC',           league: 'Ligue 1',          country: 'FR', tier: 'low', ovr: 74 },
  { id: 'strasbourg',   name: 'RC Strasbourg',         league: 'Ligue 1',          country: 'FR', tier: 'low', ovr: 74 },
  // ---------------- Liga Portugal (6) ---------------------------------
  { id: 'benfica',      name: 'SL Benfica',            league: 'Liga Portugal',    country: 'PT', tier: 'top', ovr: 80 },
  { id: 'porto',        name: 'FC Porto',              league: 'Liga Portugal',    country: 'PT', tier: 'top', ovr: 79 },
  { id: 'sporting',     name: 'Sporting CP',           league: 'Liga Portugal',    country: 'PT', tier: 'top', ovr: 80 },
  { id: 'braga',        name: 'SC Braga',              league: 'Liga Portugal',    country: 'PT', tier: 'mid', ovr: 76 },
  { id: 'vitoria',      name: 'Vitória SC',            league: 'Liga Portugal',    country: 'PT', tier: 'low', ovr: 73 },
  { id: 'boavista',     name: 'Boavista FC',           league: 'Liga Portugal',    country: 'PT', tier: 'low', ovr: 71 },
  // ---------------- Eredivisie (6) ------------------------------------
  { id: 'ajax',         name: 'Ajax',                  league: 'Eredivisie',       country: 'NL', tier: 'top', ovr: 79 },
  { id: 'psv',          name: 'PSV Eindhoven',         league: 'Eredivisie',       country: 'NL', tier: 'top', ovr: 80 },
  { id: 'feyenoord',    name: 'Feyenoord',             league: 'Eredivisie',       country: 'NL', tier: 'mid', ovr: 78 },
  { id: 'azalkmaar',    name: 'AZ Alkmaar',            league: 'Eredivisie',       country: 'NL', tier: 'mid', ovr: 76 },
  { id: 'twente',       name: 'FC Twente',             league: 'Eredivisie',       country: 'NL', tier: 'low', ovr: 74 },
  { id: 'utrecht',      name: 'FC Utrecht',            league: 'Eredivisie',       country: 'NL', tier: 'low', ovr: 73 },
  // ---------------- Saudi Pro League (5) -------------------------------
  { id: 'alnassr',      name: 'Al-Nassr',              league: 'Saudi Pro League', country: 'SA', tier: 'top', ovr: 80 },
  { id: 'alhilal',      name: 'Al-Hilal',              league: 'Saudi Pro League', country: 'SA', tier: 'top', ovr: 82 },
  { id: 'alittihad',    name: 'Al-Ittihad',            league: 'Saudi Pro League', country: 'SA', tier: 'top', ovr: 79 },
  { id: 'alahli',       name: 'Al-Ahli',               league: 'Saudi Pro League', country: 'SA', tier: 'mid', ovr: 78 },
  { id: 'alqadsiah',    name: 'Al-Qadsiah',            league: 'Saudi Pro League', country: 'SA', tier: 'mid', ovr: 76 },
  // ---------------- MLS (6) --------------------------------------------
  { id: 'intermiami',   name: 'Inter Miami CF',        league: 'MLS',              country: 'US', tier: 'top', ovr: 76 },
  { id: 'lafc',         name: 'LAFC',                  league: 'MLS',              country: 'US', tier: 'mid', ovr: 74 },
  { id: 'atlanta',      name: 'Atlanta United',        league: 'MLS',              country: 'US', tier: 'mid', ovr: 73 },
  { id: 'lagalaxy',     name: 'LA Galaxy',             league: 'MLS',              country: 'US', tier: 'mid', ovr: 73 },
  { id: 'seattle',      name: 'Seattle Sounders',      league: 'MLS',              country: 'US', tier: 'mid', ovr: 73 },
  { id: 'portland',     name: 'Portland Timbers',      league: 'MLS',              country: 'US', tier: 'low', ovr: 71 },
  // ---------------- Championship (5) -----------------------------------
  { id: 'leeds',        name: 'Leeds United',          league: 'EFL Championship', country: 'EN', tier: 'mid', ovr: 74 },
  { id: 'burnley',      name: 'Burnley',               league: 'EFL Championship', country: 'EN', tier: 'mid', ovr: 73 },
  { id: 'sheffweds',    name: 'Sheffield Wednesday',   league: 'EFL Championship', country: 'EN', tier: 'low', ovr: 70 },
  { id: 'sheffutd',     name: 'Sheffield United',      league: 'EFL Championship', country: 'EN', tier: 'low', ovr: 72 },
  { id: 'norwich',      name: 'Norwich City',          league: 'EFL Championship', country: 'EN', tier: 'low', ovr: 70 },
  // ---------------- Scottish Premiership (3) ---------------------------
  { id: 'celtic',       name: 'Celtic',                league: 'Scottish Premier', country: 'SC', tier: 'mid', ovr: 76 },
  { id: 'rangers',      name: 'Rangers',               league: 'Scottish Premier', country: 'SC', tier: 'mid', ovr: 75 },
  { id: 'aberdeen',     name: 'Aberdeen',              league: 'Scottish Premier', country: 'SC', tier: 'low', ovr: 71 },
  // ---------------- Süper Lig (3) --------------------------------------
  { id: 'galatasaray',  name: 'Galatasaray',           league: 'Süper Lig',        country: 'TR', tier: 'top', ovr: 78 },
  { id: 'fenerbahce',   name: 'Fenerbahçe',            league: 'Süper Lig',        country: 'TR', tier: 'mid', ovr: 77 },
  { id: 'besiktas',     name: 'Beşiktaş',              league: 'Süper Lig',        country: 'TR', tier: 'mid', ovr: 75 },
  // ---------------- Belgian Pro League (3) -----------------------------
  { id: 'brugge',       name: 'Club Brugge',           league: 'Belgian Pro',      country: 'BE', tier: 'mid', ovr: 77 },
  { id: 'anderlecht',   name: 'RSC Anderlecht',        league: 'Belgian Pro',      country: 'BE', tier: 'mid', ovr: 74 },
  { id: 'unionsg',      name: 'Union Saint-Gilloise',  league: 'Belgian Pro',      country: 'BE', tier: 'mid', ovr: 76 },
  // ---------------- Argentine Liga Profesional (4) ---------------------
  { id: 'boca',         name: 'Boca Juniors',          league: 'Liga Profesional', country: 'AR', tier: 'mid', ovr: 75 },
  { id: 'river',        name: 'River Plate',           league: 'Liga Profesional', country: 'AR', tier: 'mid', ovr: 76 },
  { id: 'racingar',     name: 'Racing Club',           league: 'Liga Profesional', country: 'AR', tier: 'mid', ovr: 73 },
  { id: 'independiente',name: 'Independiente',         league: 'Liga Profesional', country: 'AR', tier: 'low', ovr: 72 },
];

// Rosters — real FC 26 data from SoFIFA for the top 15 teams.
// Positions are simplified: GK, DEF (CB/LB/RB), MID (CDM/CM/CAM), ATA (LW/RW/ST).
// OVRs are the exact numbers from the game.
window.FC_TEAM_ROSTERS = {
  realmadrid: [
    { name: 'T. Courtois',           pos: 'GK',  ovr: 90 },
    { name: 'A. Lunin',              pos: 'GK',  ovr: 80 },
    { name: 'T. Alexander-Arnold',   pos: 'DEF', ovr: 85 },
    { name: 'D. Carvajal',           pos: 'DEF', ovr: 84 },
    { name: 'A. Rüdiger',            pos: 'DEF', ovr: 84 },
    { name: 'É. Militão',            pos: 'DEF', ovr: 84 },
    { name: 'D. Huijsen',            pos: 'DEF', ovr: 81 },
    { name: 'Álvaro Carreras',       pos: 'DEF', ovr: 81 },
    { name: 'F. Mendy',              pos: 'DEF', ovr: 81 },
    { name: 'D. Alaba',              pos: 'DEF', ovr: 80 },
    { name: 'F. Valverde',           pos: 'MID', ovr: 89 },
    { name: 'J. Bellingham',         pos: 'MID', ovr: 89 },
    { name: 'A. Tchouaméni',         pos: 'MID', ovr: 84 },
    { name: 'E. Camavinga',          pos: 'MID', ovr: 82 },
    { name: 'A. Güler',              pos: 'MID', ovr: 82 },
    { name: 'Brahim Díaz',           pos: 'MID', ovr: 81 },
    { name: 'Dani Ceballos',         pos: 'MID', ovr: 80 },
    { name: 'K. Mbappé',             pos: 'ATA', ovr: 91 },
    { name: 'Vini Jr.',              pos: 'ATA', ovr: 89 },
    { name: 'Rodrygo',               pos: 'ATA', ovr: 84 },
    { name: 'F. Mastantuono',        pos: 'ATA', ovr: 77 },
  ],
  barcelona: [
    { name: 'Joan García',           pos: 'GK',  ovr: 85 },
    { name: 'W. Szczęsny',           pos: 'GK',  ovr: 83 },
    { name: 'J. Koundé',             pos: 'DEF', ovr: 86 },
    { name: 'João Cancelo',          pos: 'DEF', ovr: 84 },
    { name: 'A. Balde',              pos: 'DEF', ovr: 83 },
    { name: 'Pau Cubarsí',           pos: 'DEF', ovr: 82 },
    { name: 'R. Araujo',             pos: 'DEF', ovr: 82 },
    { name: 'Eric García',           pos: 'DEF', ovr: 82 },
    { name: 'A. Christensen',        pos: 'DEF', ovr: 80 },
    { name: 'Pedri',                 pos: 'MID', ovr: 90 },
    { name: 'F. de Jong',            pos: 'MID', ovr: 87 },
    { name: 'Dani Olmo',             pos: 'MID', ovr: 84 },
    { name: 'Gavi',                  pos: 'MID', ovr: 83 },
    { name: 'Fermín López',          pos: 'MID', ovr: 82 },
    { name: 'Marc Casadó',           pos: 'MID', ovr: 79 },
    { name: 'Lamine Yamal',          pos: 'ATA', ovr: 89 },
    { name: 'Raphinha',              pos: 'ATA', ovr: 89 },
    { name: 'R. Lewandowski',        pos: 'ATA', ovr: 87 },
    { name: 'Ferran Torres',         pos: 'ATA', ovr: 84 },
    { name: 'M. Rashford',           pos: 'ATA', ovr: 81 },
  ],
  mancity: [
    { name: 'G. Donnarumma',         pos: 'GK',  ovr: 89 },
    { name: 'J. Trafford',           pos: 'GK',  ovr: 76 },
    { name: 'Rúben Dias',            pos: 'DEF', ovr: 86 },
    { name: 'J. Gvardiol',           pos: 'DEF', ovr: 85 },
    { name: 'M. Guéhi',              pos: 'DEF', ovr: 83 },
    { name: 'N. Aké',                pos: 'DEF', ovr: 82 },
    { name: 'J. Stones',             pos: 'DEF', ovr: 82 },
    { name: 'R. Aït-Nouri',          pos: 'DEF', ovr: 81 },
    { name: 'Matheus Nunes',         pos: 'DEF', ovr: 81 },
    { name: 'A. Khusanov',           pos: 'DEF', ovr: 79 },
    { name: 'Rodri',                 pos: 'MID', ovr: 90 },
    { name: 'P. Foden',              pos: 'MID', ovr: 85 },
    { name: 'T. Reijnders',          pos: 'MID', ovr: 85 },
    { name: 'Bernardo Silva',        pos: 'MID', ovr: 84 },
    { name: 'M. Kovačić',            pos: 'MID', ovr: 82 },
    { name: 'R. Cherki',             pos: 'MID', ovr: 81 },
    { name: 'Nico González',         pos: 'MID', ovr: 80 },
    { name: 'E. Haaland',            pos: 'ATA', ovr: 91 },
    { name: 'O. Marmoush',           pos: 'ATA', ovr: 83 },
    { name: 'J. Doku',               pos: 'ATA', ovr: 83 },
    { name: 'Savinho',               pos: 'ATA', ovr: 81 },
    { name: 'A. Semenyo',            pos: 'ATA', ovr: 83 },
  ],
  bayern: [
    { name: 'M. Neuer',              pos: 'GK',  ovr: 84 },
    { name: 'J. Urbig',              pos: 'GK',  ovr: 74 },
    { name: 'J. Tah',                pos: 'DEF', ovr: 87 },
    { name: 'D. Upamecano',          pos: 'DEF', ovr: 85 },
    { name: 'A. Davies',             pos: 'DEF', ovr: 84 },
    { name: 'M. Guéhi',              pos: 'DEF', ovr: 82 },
    { name: 'K. Laimer',             pos: 'DEF', ovr: 82 },
    { name: 'H. Ito',                pos: 'DEF', ovr: 78 },
    { name: 'J. Stanišić',           pos: 'DEF', ovr: 78 },
    { name: 'S. Boey',               pos: 'DEF', ovr: 77 },
    { name: 'J. Kimmich',            pos: 'MID', ovr: 89 },
    { name: 'J. Musiala',            pos: 'MID', ovr: 88 },
    { name: 'A. Pavlović',           pos: 'MID', ovr: 79 },
    { name: 'T. Bischof',            pos: 'MID', ovr: 76 },
    { name: 'H. Kane',               pos: 'ATA', ovr: 89 },
    { name: 'M. Olise',              pos: 'ATA', ovr: 86 },
    { name: 'L. Díaz',               pos: 'ATA', ovr: 85 },
    { name: 'S. Gnabry',             pos: 'ATA', ovr: 82 },
    { name: 'N. Jackson',            pos: 'ATA', ovr: 80 },
    { name: 'M. Fofana',             pos: 'ATA', ovr: 78 },
    { name: 'L. Karl',               pos: 'ATA', ovr: 65 },
  ],
  psg: [
    { name: 'L. Chevalier',          pos: 'GK',  ovr: 83 },
    { name: 'M. Safonov',            pos: 'GK',  ovr: 78 },
    { name: 'Marquinhos',            pos: 'DEF', ovr: 87 },
    { name: 'W. Pacho',              pos: 'DEF', ovr: 86 },
    { name: 'Nuno Mendes',           pos: 'DEF', ovr: 86 },
    { name: 'A. Hakimi',             pos: 'DEF', ovr: 89 },
    { name: 'L. Hernández',          pos: 'DEF', ovr: 81 },
    { name: 'I. Zabarnyi',           pos: 'DEF', ovr: 79 },
    { name: 'L. Beraldo',            pos: 'DEF', ovr: 78 },
    { name: 'Vitinha',               pos: 'MID', ovr: 89 },
    { name: 'João Neves',            pos: 'MID', ovr: 85 },
    { name: 'Fabián Ruiz',           pos: 'MID', ovr: 85 },
    { name: 'W. Zaïre-Emery',        pos: 'MID', ovr: 80 },
    { name: 'O. Dembélé',            pos: 'ATA', ovr: 90 },
    { name: 'K. Kvaratskhelia',      pos: 'ATA', ovr: 87 },
    { name: 'D. Doué',               pos: 'ATA', ovr: 85 },
    { name: 'B. Barcola',            pos: 'ATA', ovr: 84 },
    { name: 'Gonçalo Ramos',         pos: 'ATA', ovr: 80 },
    { name: 'Lee Kang-in',           pos: 'ATA', ovr: 80 },
  ],
  liverpool: [
    { name: 'Alisson',               pos: 'GK',  ovr: 89 },
    { name: 'G. Mamardashvili',      pos: 'GK',  ovr: 84 },
    { name: 'V. van Dijk',           pos: 'DEF', ovr: 90 },
    { name: 'I. Konaté',             pos: 'DEF', ovr: 85 },
    { name: 'A. Robertson',          pos: 'DEF', ovr: 81 },
    { name: 'M. Kerkez',             pos: 'DEF', ovr: 81 },
    { name: 'J. Frimpong',           pos: 'DEF', ovr: 83 },
    { name: 'J. Gomez',              pos: 'DEF', ovr: 79 },
    { name: 'C. Bradley',            pos: 'DEF', ovr: 78 },
    { name: 'R. Gravenberch',        pos: 'MID', ovr: 86 },
    { name: 'A. Mac Allister',       pos: 'MID', ovr: 86 },
    { name: 'D. Szoboszlai',         pos: 'MID', ovr: 84 },
    { name: 'C. Jones',              pos: 'MID', ovr: 80 },
    { name: 'W. Endo',               pos: 'MID', ovr: 79 },
    { name: 'M. Salah',              pos: 'ATA', ovr: 90 },
    { name: 'A. Isak',               pos: 'ATA', ovr: 88 },
    { name: 'F. Wirtz',              pos: 'ATA', ovr: 88 },
    { name: 'C. Gakpo',              pos: 'ATA', ovr: 84 },
    { name: 'H. Ekitiké',            pos: 'ATA', ovr: 83 },
    { name: 'F. Chiesa',             pos: 'ATA', ovr: 81 },
  ],
  arsenal: [
    { name: 'David Raya',            pos: 'GK',  ovr: 87 },
    { name: 'K. Arrizabalaga',       pos: 'GK',  ovr: 78 },
    { name: 'Gabriel Magalhães',     pos: 'DEF', ovr: 89 },
    { name: 'W. Saliba',             pos: 'DEF', ovr: 88 },
    { name: 'J. Timber',             pos: 'DEF', ovr: 84 },
    { name: 'R. Calafiori',          pos: 'DEF', ovr: 82 },
    { name: 'P. Hincapié',           pos: 'DEF', ovr: 83 },
    { name: 'C. Lukeba',             pos: 'DEF', ovr: 81 },
    { name: 'T. Livramento',         pos: 'DEF', ovr: 80 },
    { name: 'C. Mosquera',           pos: 'DEF', ovr: 77 },
    { name: 'D. Rice',               pos: 'MID', ovr: 88 },
    { name: 'M. Ødegaard',           pos: 'MID', ovr: 86 },
    { name: 'Zubimendi',             pos: 'MID', ovr: 85 },
    { name: 'M. Merino',             pos: 'MID', ovr: 83 },
    { name: 'M. Lewis-Skelly',       pos: 'MID', ovr: 78 },
    { name: 'E. Nwaneri',            pos: 'MID', ovr: 76 },
    { name: 'B. Saka',               pos: 'ATA', ovr: 87 },
    { name: 'V. Gyökeres',           pos: 'ATA', ovr: 86 },
    { name: 'E. Eze',                pos: 'ATA', ovr: 84 },
    { name: 'K. Havertz',            pos: 'ATA', ovr: 82 },
    { name: 'G. Martinelli',         pos: 'ATA', ovr: 81 },
    { name: 'N. Madueke',            pos: 'ATA', ovr: 80 },
  ],
  inter: [
    { name: 'Y. Sommer',             pos: 'GK',  ovr: 87 },
    { name: 'Josep Martínez',        pos: 'GK',  ovr: 75 },
    { name: 'A. Bastoni',            pos: 'DEF', ovr: 87 },
    { name: 'F. Dimarco',            pos: 'DEF', ovr: 85 },
    { name: 'D. Dumfries',           pos: 'DEF', ovr: 84 },
    { name: 'F. Acerbi',             pos: 'DEF', ovr: 84 },
    { name: 'S. de Vrij',            pos: 'DEF', ovr: 83 },
    { name: 'M. Akanji',             pos: 'DEF', ovr: 82 },
    { name: 'Carlos Augusto',        pos: 'DEF', ovr: 81 },
    { name: 'M. Darmian',            pos: 'DEF', ovr: 80 },
    { name: 'N. Barella',            pos: 'MID', ovr: 87 },
    { name: 'H. Çalhanoğlu',         pos: 'MID', ovr: 86 },
    { name: 'H. Mkhitaryan',         pos: 'MID', ovr: 83 },
    { name: 'D. Frattesi',           pos: 'MID', ovr: 81 },
    { name: 'P. Zieliński',          pos: 'MID', ovr: 80 },
    { name: 'P. Sučić',              pos: 'MID', ovr: 76 },
    { name: 'L. Martínez',           pos: 'ATA', ovr: 88 },
    { name: 'M. Thuram',             pos: 'ATA', ovr: 85 },
    { name: 'Luis Henrique',         pos: 'ATA', ovr: 78 },
    { name: 'Y. Bonny',              pos: 'ATA', ovr: 77 },
  ],
  napoli: [
    { name: 'A. Meret',              pos: 'GK',  ovr: 82 },
    { name: 'V. Milinković-Savić',   pos: 'GK',  ovr: 79 },
    { name: 'G. Di Lorenzo',         pos: 'DEF', ovr: 83 },
    { name: 'A. Rrahmani',           pos: 'DEF', ovr: 83 },
    { name: 'A. Buongiorno',         pos: 'DEF', ovr: 82 },
    { name: 'Miguel Gutiérrez',      pos: 'DEF', ovr: 81 },
    { name: 'L. Spinazzola',         pos: 'DEF', ovr: 80 },
    { name: 'M. Olivera',            pos: 'DEF', ovr: 77 },
    { name: 'S. Beukema',            pos: 'DEF', ovr: 77 },
    { name: 'K. De Bruyne',          pos: 'MID', ovr: 87 },
    { name: 'S. McTominay',          pos: 'MID', ovr: 86 },
    { name: 'S. Lobotka',            pos: 'MID', ovr: 83 },
    { name: 'A. Zambo Anguissa',     pos: 'MID', ovr: 83 },
    { name: 'David Neres',           pos: 'MID', ovr: 81 },
    { name: 'M. Politano',           pos: 'MID', ovr: 81 },
    { name: 'B. Gilmour',            pos: 'MID', ovr: 74 },
    { name: 'R. Lukaku',             pos: 'ATA', ovr: 83 },
    { name: 'R. Højlund',            pos: 'ATA', ovr: 77 },
    { name: 'E. Elmas',              pos: 'ATA', ovr: 77 },
  ],
  chelsea: [
    { name: 'Robert Sánchez',        pos: 'GK',  ovr: 81 },
    { name: 'F. Jörgensen',          pos: 'GK',  ovr: 77 },
    { name: 'R. James',              pos: 'DEF', ovr: 84 },
    { name: 'Marc Cucurella',        pos: 'DEF', ovr: 85 },
    { name: 'L. Colwill',            pos: 'DEF', ovr: 80 },
    { name: 'T. Chalobah',           pos: 'DEF', ovr: 80 },
    { name: 'W. Fofana',             pos: 'DEF', ovr: 79 },
    { name: 'M. Gusto',              pos: 'DEF', ovr: 79 },
    { name: 'J. Hato',               pos: 'DEF', ovr: 78 },
    { name: 'T. Adarabioyo',         pos: 'DEF', ovr: 78 },
    { name: 'M. Sarr',               pos: 'DEF', ovr: 77 },
    { name: 'M. Caicedo',            pos: 'MID', ovr: 88 },
    { name: 'E. Fernández',          pos: 'MID', ovr: 85 },
    { name: 'Andrey Santos',         pos: 'MID', ovr: 80 },
    { name: 'R. Lavia',              pos: 'MID', ovr: 78 },
    { name: 'C. Palmer',             pos: 'ATA', ovr: 86 },
    { name: 'Pedro Neto',            pos: 'ATA', ovr: 82 },
    { name: 'João Pedro',            pos: 'ATA', ovr: 82 },
    { name: 'Estêvão',               pos: 'ATA', ovr: 79 },
    { name: 'A. Garnacho',           pos: 'ATA', ovr: 78 },
    { name: 'J. Gittens',            pos: 'ATA', ovr: 78 },
    { name: 'L. Delap',              pos: 'ATA', ovr: 77 },
  ],
  atleti: [
    { name: 'J. Oblak',              pos: 'GK',  ovr: 88 },
    { name: 'J. Musso',              pos: 'GK',  ovr: 79 },
    { name: 'D. Hancko',             pos: 'DEF', ovr: 83 },
    { name: 'J. Giménez',            pos: 'DEF', ovr: 83 },
    { name: 'M. Llorente',           pos: 'DEF', ovr: 84 },
    { name: 'R. Le Normand',         pos: 'DEF', ovr: 81 },
    { name: 'C. Lenglet',            pos: 'DEF', ovr: 78 },
    { name: 'N. Molina',             pos: 'DEF', ovr: 77 },
    { name: 'Pubill',                pos: 'DEF', ovr: 78 },
    { name: 'M. Ruggeri',            pos: 'DEF', ovr: 78 },
    { name: 'Pablo Barrios',         pos: 'MID', ovr: 83 },
    { name: 'Koke',                  pos: 'MID', ovr: 81 },
    { name: 'Johnny Cardoso',        pos: 'MID', ovr: 80 },
    { name: 'T. Almada',             pos: 'MID', ovr: 79 },
    { name: 'Álex Baena',            pos: 'MID', ovr: 83 },
    { name: 'N. González',           pos: 'MID', ovr: 79 },
    { name: 'J. Álvarez',            pos: 'ATA', ovr: 87 },
    { name: 'A. Griezmann',          pos: 'ATA', ovr: 84 },
    { name: 'A. Sørloth',            pos: 'ATA', ovr: 83 },
    { name: 'A. Lookman',            pos: 'ATA', ovr: 83 },
    { name: 'Giuliano Simeone',      pos: 'ATA', ovr: 82 },
  ],
  juventus: [
    { name: 'M. Di Gregorio',        pos: 'GK',  ovr: 81 },
    { name: 'M. Perin',              pos: 'GK',  ovr: 78 },
    { name: 'Bremer',                pos: 'DEF', ovr: 86 },
    { name: 'F. Gatti',              pos: 'DEF', ovr: 80 },
    { name: 'P. Kalulu',             pos: 'DEF', ovr: 80 },
    { name: 'A. Cambiaso',           pos: 'DEF', ovr: 80 },
    { name: 'F. Kostić',             pos: 'DEF', ovr: 80 },
    { name: 'J. Cabal',              pos: 'DEF', ovr: 74 },
    { name: 'L. Kelly',              pos: 'DEF', ovr: 77 },
    { name: 'M. Locatelli',          pos: 'MID', ovr: 84 },
    { name: 'K. Thuram',             pos: 'MID', ovr: 81 },
    { name: 'T. Koopmeiners',        pos: 'MID', ovr: 80 },
    { name: 'W. McKennie',           pos: 'MID', ovr: 78 },
    { name: 'F. Miretti',            pos: 'MID', ovr: 75 },
    { name: 'L. Openda',             pos: 'ATA', ovr: 82 },
    { name: 'J. David',              pos: 'ATA', ovr: 81 },
    { name: 'D. Vlahović',           pos: 'ATA', ovr: 81 },
    { name: 'K. Yıldız',             pos: 'ATA', ovr: 81 },
    { name: 'Francisco Conceição',   pos: 'ATA', ovr: 79 },
    { name: 'E. Zhegrova',           pos: 'ATA', ovr: 79 },
  ],
  milan: [
    { name: 'M. Maignan',            pos: 'GK',  ovr: 87 },
    { name: 'P. Terracciano',        pos: 'GK',  ovr: 78 },
    { name: 'F. Tomori',             pos: 'DEF', ovr: 81 },
    { name: 'M. Gabbia',             pos: 'DEF', ovr: 80 },
    { name: 'A. Saelemaekers',       pos: 'DEF', ovr: 80 },
    { name: 'P. Estupiñán',          pos: 'DEF', ovr: 79 },
    { name: 'S. Pavlović',           pos: 'DEF', ovr: 77 },
    { name: 'K. De Winter',          pos: 'DEF', ovr: 75 },
    { name: 'D. Bartesaghi',         pos: 'DEF', ovr: 71 },
    { name: 'A. Rabiot',             pos: 'MID', ovr: 85 },
    { name: 'L. Modrić',             pos: 'MID', ovr: 85 },
    { name: 'Y. Fofana',             pos: 'MID', ovr: 81 },
    { name: 'R. Loftus-Cheek',       pos: 'MID', ovr: 80 },
    { name: 'S. Ricci',              pos: 'MID', ovr: 79 },
    { name: 'A. Jashari',            pos: 'MID', ovr: 77 },
    { name: 'C. Pulisic',            pos: 'ATA', ovr: 85 },
    { name: 'Rafael Leão',           pos: 'ATA', ovr: 84 },
    { name: 'C. Nkunku',             pos: 'ATA', ovr: 81 },
    { name: 'S. Giménez',            pos: 'ATA', ovr: 79 },
    { name: 'N. Füllkrug',           pos: 'ATA', ovr: 78 },
  ],
  manutd: [
    { name: 'S. Lammens',            pos: 'GK',  ovr: 76 },
    { name: 'A. Bayındır',           pos: 'GK',  ovr: 76 },
    { name: 'M. de Ligt',            pos: 'DEF', ovr: 84 },
    { name: 'D. Dumfries',           pos: 'DEF', ovr: 83 },
    { name: 'N. Mazraoui',           pos: 'DEF', ovr: 83 },
    { name: 'L. Martínez',           pos: 'DEF', ovr: 82 },
    { name: 'L. Shaw',               pos: 'DEF', ovr: 80 },
    { name: 'H. Maguire',            pos: 'DEF', ovr: 80 },
    { name: 'Diogo Dalot',           pos: 'DEF', ovr: 80 },
    { name: 'L. Yoro',               pos: 'DEF', ovr: 78 },
    { name: 'P. Dorgu',              pos: 'DEF', ovr: 76 },
    { name: 'Bruno Fernandes',       pos: 'MID', ovr: 88 },
    { name: 'C. Baleba',             pos: 'MID', ovr: 81 },
    { name: 'M. Ugarte',             pos: 'MID', ovr: 80 },
    { name: 'M. Mount',              pos: 'MID', ovr: 77 },
    { name: 'K. Mainoo',             pos: 'MID', ovr: 77 },
    { name: 'Matheus Cunha',         pos: 'ATA', ovr: 84 },
    { name: 'B. Mbeumo',             pos: 'ATA', ovr: 84 },
    { name: 'B. Šeško',              pos: 'ATA', ovr: 82 },
    { name: 'A. Robinson',           pos: 'ATA', ovr: 82 },
    { name: 'J. Zirkzee',            pos: 'ATA', ovr: 77 },
    { name: 'Amad Diallo',           pos: 'ATA', ovr: 79 },
  ],
  dortmund: [
    { name: 'G. Kobel',              pos: 'GK',  ovr: 86 },
    { name: 'A. Meyer',              pos: 'GK',  ovr: 75 },
    { name: 'N. Schlotterbeck',      pos: 'DEF', ovr: 86 },
    { name: 'W. Anton',              pos: 'DEF', ovr: 83 },
    { name: 'E. Can',                pos: 'DEF', ovr: 82 },
    { name: 'R. Bensebaini',         pos: 'DEF', ovr: 80 },
    { name: 'J. Ryerson',            pos: 'DEF', ovr: 80 },
    { name: 'Yan Couto',             pos: 'DEF', ovr: 79 },
    { name: 'N. Süle',               pos: 'DEF', ovr: 78 },
    { name: 'F. Nmecha',             pos: 'MID', ovr: 84 },
    { name: 'J. Brandt',             pos: 'MID', ovr: 83 },
    { name: 'M. Sabitzer',           pos: 'MID', ovr: 81 },
    { name: 'D. Svensson',           pos: 'MID', ovr: 79 },
    { name: 'J. Bellingham',         pos: 'MID', ovr: 77 },
    { name: 'C. Chukwuemeka',        pos: 'MID', ovr: 78 },
    { name: 'S. Guirassy',           pos: 'ATA', ovr: 85 },
    { name: 'K. Adeyemi',            pos: 'ATA', ovr: 82 },
    { name: 'M. Beier',              pos: 'ATA', ovr: 80 },
    { name: 'Fábio Silva',           pos: 'ATA', ovr: 79 },
  ],
};

// Helper — returns roster for a catalog team id, or [] if none is registered.
window.FC_TEAM_ROSTER = function (catalogId) {
  return (window.FC_TEAM_ROSTERS && window.FC_TEAM_ROSTERS[catalogId]) || [];
};
window.FC_TEAM_BY_ID = function (catalogId) {
  return (window.FC_TEAM_CATALOG || []).find(t => t.id === catalogId) || null;
};
